# Copyright (C) 2026 K2-OpenHost contributors
# This file may be distributed under the terms of the GNU GPLv3 license.
"""K2-OpenHost: OrcaSlicer preset IDs for CFS filaments.

OrcaSlicer selects a filament preset by its ``filament_id``. Every CFS
filament gets one, without renaming anything: the filament's own ID, name,
brand and RFID codes stay the keys of RFID and spool tracking.

* Default: from config/k2/orca_k2pro_filament_ids.json (generated by
  scripts/generate_orca_filament_ids.py from OrcaSlicer's K2 Pro presets):
  the catalog filament's own preset, a Bambu tag's product in the
  OrcaSlicer filament library ("Bambulab PETG HF" -> "Bambu PETG HF
  @System"), or a preset with the profile's name.
* Override: set per filament from Mainsail or _BOX_FILAMENT_ORCA_ID, kept in
  the filament library file, also for read-only system profiles.

A slot without a profile uses the generic preset of its material.
"""

import json
import logging
import os
import re

ORCA_ID_RE = re.compile(r"^[A-Za-z0-9_.+-]{1,40}$")
BAMBU_BRANDS = ("BAMBULAB", "BAMBU LAB", "BAMBU")
PRESET_SUFFIXES = (" @K2 Pro-all", " @System")


def clean_orca_id(value):
    """A valid OrcaSlicer filament_id, "" for none; raise ValueError."""
    text = str(value or "").strip()
    if text and not ORCA_ID_RE.match(text):
        raise ValueError("invalid OrcaSlicer filament_id %r" % text)
    return text


class OrcaPresetTable:
    """OrcaSlicer presets usable on the K2 Pro, and the default per filament."""

    def __init__(self, path=None):
        self.path = path
        self.source = ""
        self.error = ""
        self.filaments = {}
        self.materials = {}
        self.presets = []
        self._by_id = {}
        self._by_name = {}
        if path:
            self.load(path)

    def load(self, path):
        try:
            with open(path, "r", encoding="utf-8") as stream:
                data = json.load(stream)
        except (OSError, ValueError) as exc:
            if os.path.exists(path):
                self.error = "%s: %s" % (path, exc)
                logging.warning("box: OrcaSlicer preset table %s", self.error)
            return
        self.source = str(data.get("source") or "")
        self.filaments = {
            str(key).strip().upper(): value
            for key, value in (data.get("filaments") or {}).items()
            if isinstance(value, dict) and value.get("orca_filament_id")}
        self.materials = {
            str(key).strip().upper(): value
            for key, value in (data.get("materials") or {}).items()
            if isinstance(value, dict) and value.get("orca_filament_id")}
        self.presets = []
        for item in data.get("presets") or []:
            if not isinstance(item, dict) or not item.get("orca_filament_id"):
                continue
            preset = {
                "id": str(item["orca_filament_id"]),
                "name": str(item.get("orca_preset") or ""),
                "type": str(item.get("orca_filament_type") or ""),
                "vendor": str(item.get("vendor") or ""),
            }
            self.presets.append(preset)
            self._by_id.setdefault(preset["id"], preset)
            self._by_name.setdefault(preset["name"].upper(), preset)

    def preset_name(self, orca_id):
        preset = self._by_id.get(str(orca_id or ""))
        return preset["name"] if preset else ""

    def _by_preset_name(self, *names):
        for name in names:
            name = " ".join(str(name or "").split())
            if not name:
                continue
            for suffix in PRESET_SUFFIXES:
                preset = self._by_name.get((name + suffix).upper())
                if preset:
                    return preset["id"]
        return ""

    def default_for(self, filament):
        """Default OrcaSlicer filament_id of a filament profile, or ""."""
        filament = filament or {}
        entry = self.filaments.get(str(filament.get("id") or "").upper())
        if entry:
            return entry["orca_filament_id"]
        brand = " ".join(str(filament.get("brand") or "").split())
        name = " ".join(str(filament.get("name") or "").split())
        if brand.upper() in BAMBU_BRANDS or name.upper().startswith(BAMBU_BRANDS):
            product = name
            for prefix in BAMBU_BRANDS:
                if product.upper().startswith(prefix + " "):
                    product = product[len(prefix) + 1:]
                    break
            found = self._by_preset_name("Bambu " + product)
            if found:
                return found
        candidates = [name]
        if brand and not name.upper().startswith(brand.upper()):
            candidates.append(brand + " " + name)
        return self._by_preset_name(*candidates)

    def material_default(self, material):
        entry = self.materials.get(str(material or "").strip().upper())
        return entry["orca_filament_id"] if entry else ""

    @property
    def presets_status(self):
        return self.presets
